[versions]
agp = "8.9.1"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
lifecycle = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
room = "2.7.0"
coroutines = "1.7.3"
mockk = "1.13.9"
navigation = "2.7.7"
kotlinTest = "2.1.10"
androidxTestCore = "1.5.0"
androidxTestRunner = "1.5.2"
androidxTestRules = "1.5.0"
androidxTestExt = "1.1.5"
coreKtxVersion = "1.6.1"
jetbrainsKotlinJvm = "2.1.10"
junitJupiter = "5.8.1"
kotlinLogging = "3.0.5"
logback = "1.4.7"
log4j = "2.23.0"
timberv = "5.0.1"
webrtc = "1.0.32006"
stream_webrtc = "1.1.1"
socket_io = "2.0.0"
firebaseDatabaseKtx = "21.0.0"
firebaseBom = "33.0.0"
gson = "2.10.1"
sqlcipher = "4.5.4"
androidx-sqlite = "2.4.0"
zxing = "3.5.1"
camerax = "1.4.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# Testing
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version = "2.2.0" }
androidx-test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }

# Navigation
androidx-navigation-compose = {group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

# Logging
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
#log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
#log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
#log4j-android = { group = "org.apache.logging.log4j", name = "log4j-android", version.ref = "log4j" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberv" }

# Network
webrtc = { group = "org.webrtc", name = "google-webrtc", version.ref = "webrtc" }
stream-webrtc = { group = "io.getstream", name = "stream-webrtc-android", version.ref = "stream_webrtc" }
socket-io = { group = "io.socket", name = "socket.io-client", version.ref = "socket_io" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }

# JSON
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Crypto
sqlcipher = { group = "net.zetetic", name = "android-database-sqlcipher", version.ref = "sqlcipher" }
androidx-sqlite = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "androidx-sqlite" }

# QRCode
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }